export interface McpConnector {
  id: string;
  name: string;
  purpose: string;
  tools: string[];
  boundCapability: string;
  allowedRoles: string[];
  status: 'planned' | 'mock' | 'sandbox_ready' | 'live_disabled';
  direction: 'read_only' | 'prepare_only' | 'write_blocked';
  requiresApproval: boolean;
  requiresM5: boolean;
  sourceOfTruth: string;
  credentialStatus: 'configured' | 'missing' | 'not_required';
  lastHealthCheck: string;
  externalExecution: string;
  envVars: string[];
}

export interface McpSkill {
  id: string;
  name: string;
  source: 'stitch_native' | 'mcp_imported' | 'planned_mcp';
  owningCapability: string;
  boundConnector: string | null;
  allowedRole: string;
  inputData: string;
  outputArtifact: string;
  requiresApproval: boolean;
  canCallExternal: boolean;
  status: 'working' | 'mock' | 'planned' | 'sandbox_ready';
  auditEnabled: boolean;
  saifRequired: boolean;
}

export const MCP_CONNECTORS: McpConnector[] = [
  {
    id: 'mcp-social-intelligence',
    name: 'Social Intelligence MCP',
    purpose: 'Platform algorithm rules, trend analysis, audience insights',
    tools: ['analyze_trends', 'get_audience_insights', 'platform_rules'],
    boundCapability: 'AnalyzeAudience',
    allowedRoles: ['specialist', 'department_head', 'admin'],
    status: 'planned',
    direction: 'read_only',
    requiresApproval: false,
    requiresM5: false,
    sourceOfTruth: 'STITCH',
    credentialStatus: 'missing',
    lastHealthCheck: 'Mock — no external call',
    externalExecution: 'Blocked',
    envVars: ['SOCIAL_INTEL_API_KEY'],
  },
  {
    id: 'mcp-content-intelligence',
    name: 'Content Intelligence MCP',
    purpose: 'Content optimization, brand voice validation, competitor analysis',
    tools: ['optimize_content', 'validate_brand_voice', 'analyze_competitors'],
    boundCapability: 'GenerateContentDraft',
    allowedRoles: ['specialist', 'admin'],
    status: 'mock',
    direction: 'read_only',
    requiresApproval: false,
    requiresM5: false,
    sourceOfTruth: 'STITCH',
    credentialStatus: 'not_required',
    lastHealthCheck: 'Mock provider active',
    externalExecution: 'Blocked',
    envVars: [],
  },
  {
    id: 'mcp-reach-intelligence',
    name: 'Social Algorithm / Reach Intelligence MCP',
    purpose: 'Reach readiness scoring, best time/format/hashtag recommendations',
    tools: ['score_reach', 'recommend_time', 'recommend_format', 'check_hashtags'],
    boundCapability: 'EvaluateReachReadiness',
    allowedRoles: ['specialist', 'department_head', 'admin'],
    status: 'mock',
    direction: 'read_only',
    requiresApproval: false,
    requiresM5: false,
    sourceOfTruth: 'STITCH',
    credentialStatus: 'not_required',
    lastHealthCheck: 'Deterministic rules active',
    externalExecution: 'Blocked',
    envVars: [],
  },
  {
    id: 'mcp-postiz-scheduling',
    name: 'Postiz Scheduling MCP',
    purpose: 'Post scheduling, publishing preparation, sandbox publishing',
    tools: ['prepare_package', 'schedule_post', 'get_status'],
    boundCapability: 'PreparePublishingPackage',
    allowedRoles: ['specialist', 'department_head', 'admin'],
    status: 'sandbox_ready',
    direction: 'prepare_only',
    requiresApproval: true,
    requiresM5: false,
    sourceOfTruth: 'STITCH',
    credentialStatus: 'missing',
    lastHealthCheck: 'Mock — sandbox not connected',
    externalExecution: 'Blocked until authorized',
    envVars: ['POSTIZ_API_KEY', 'POSTIZ_URL'],
  },
  {
    id: 'mcp-social-analytics',
    name: 'Social Analytics MCP',
    purpose: 'Platform analytics ingestion, performance metrics, reporting',
    tools: ['ingest_metrics', 'get_performance', 'generate_report'],
    boundCapability: 'GenerateFinancialReport',
    allowedRoles: ['specialist', 'department_head', 'admin'],
    status: 'planned',
    direction: 'read_only',
    requiresApproval: false,
    requiresM5: false,
    sourceOfTruth: 'STITCH',
    credentialStatus: 'missing',
    lastHealthCheck: 'Mock — no external call',
    externalExecution: 'Blocked',
    envVars: ['ANALYTICS_API_KEY'],
  },
  {
    id: 'mcp-ghl-crm',
    name: 'GoHighLevel CRM MCP',
    purpose: 'Lead capture, qualification, CRM handoff, opportunity creation',
    tools: ['capture_lead', 'qualify_lead', 'create_contact', 'create_opportunity'],
    boundCapability: 'CaptureLead',
    allowedRoles: ['specialist', 'department_head', 'admin'],
    status: 'planned',
    direction: 'write_blocked',
    requiresApproval: true,
    requiresM5: true,
    sourceOfTruth: 'STITCH',
    credentialStatus: 'missing',
    lastHealthCheck: 'Mock — no external call',
    externalExecution: 'Blocked',
    envVars: ['GHL_API_KEY', 'GHL_LOCATION_ID', 'GHL_PIPELINE_ID'],
  },
  {
    id: 'mcp-lead-qualification',
    name: 'Lead Qualification MCP',
    purpose: 'Lead scoring, qualification rules, attribution',
    tools: ['score_lead', 'qualify_lead', 'attribute_campaign'],
    boundCapability: 'CaptureLead',
    allowedRoles: ['specialist', 'admin'],
    status: 'mock',
    direction: 'read_only',
    requiresApproval: false,
    requiresM5: false,
    sourceOfTruth: 'STITCH',
    credentialStatus: 'not_required',
    lastHealthCheck: 'Mock rules active',
    externalExecution: 'Blocked',
    envVars: [],
  },
  {
    id: 'mcp-whatsapp',
    name: 'WhatsApp Messaging MCP',
    purpose: 'WhatsApp handoff, message preparation, template management',
    tools: ['prepare_message', 'send_template', 'get_status'],
    boundCapability: 'CaptureLead',
    allowedRoles: ['specialist', 'department_head', 'admin'],
    status: 'planned',
    direction: 'write_blocked',
    requiresApproval: true,
    requiresM5: true,
    sourceOfTruth: 'STITCH',
    credentialStatus: 'missing',
    lastHealthCheck: 'Mock — no external call',
    externalExecution: 'Blocked',
    envVars: ['WHATSAPP_API_KEY', 'WHATSAPP_PHONE_ID'],
  },
  {
    id: 'mcp-voice-chat',
    name: 'Voice/Chat Agent API MCP',
    purpose: 'AI voice agent handoff, chat agent handoff, engagement surface',
    tools: ['trigger_voice', 'trigger_chat', 'prepare_handoff'],
    boundCapability: 'CaptureLead',
    allowedRoles: ['department_head', 'admin'],
    status: 'planned',
    direction: 'write_blocked',
    requiresApproval: true,
    requiresM5: true,
    sourceOfTruth: 'STITCH',
    credentialStatus: 'missing',
    lastHealthCheck: 'Mock — no external call',
    externalExecution: 'Blocked',
    envVars: ['VOICE_AGENT_API_KEY', 'CHAT_AGENT_API_KEY'],
  },
  {
    id: 'mcp-resourcespace',
    name: 'ResourceSpace MCP',
    purpose: 'Digital asset management, asset search, asset retrieval',
    tools: ['search_assets', 'get_asset', 'upload_asset'],
    boundCapability: 'ManageAsset',
    allowedRoles: ['specialist', 'admin'],
    status: 'planned',
    direction: 'read_only',
    requiresApproval: false,
    requiresM5: false,
    sourceOfTruth: 'STITCH',
    credentialStatus: 'missing',
    lastHealthCheck: 'Mock — no external call',
    externalExecution: 'Blocked',
    envVars: ['RESOURCESPACE_API_KEY', 'RESOURCESPACE_URL'],
  },
  {
    id: 'mcp-paperclip',
    name: 'Paperclip MCP',
    purpose: 'Operating surface integration, task relay, workflow coordination',
    tools: ['create_task', 'get_status', 'relay_message'],
    boundCapability: 'ManageCampaign',
    allowedRoles: ['specialist', 'admin'],
    status: 'planned',
    direction: 'read_only',
    requiresApproval: false,
    requiresM5: false,
    sourceOfTruth: 'STITCH',
    credentialStatus: 'missing',
    lastHealthCheck: 'Mock — no external call',
    externalExecution: 'Blocked',
    envVars: ['PAPERCLIP_API_KEY'],
  },
  {
    id: 'mcp-rendering',
    name: 'Rendering/Production MCP',
    purpose: 'Visual content rendering, design asset generation, production preparation',
    tools: ['render_image', 'render_video', 'prepare_package'],
    boundCapability: 'RenderContent',
    allowedRoles: ['specialist', 'department_head', 'admin'],
    status: 'planned',
    direction: 'prepare_only',
    requiresApproval: true,
    requiresM5: false,
    sourceOfTruth: 'STITCH',
    credentialStatus: 'missing',
    lastHealthCheck: 'Mock — no external call',
    externalExecution: 'Blocked',
    envVars: ['RENDERING_API_KEY'],
  },
];

export const MCP_SKILLS: McpSkill[] = [
  {
    id: 'skill-campaign-strategy',
    name: 'Campaign Strategy',
    source: 'stitch_native',
    owningCapability: 'ManageCampaign',
    boundConnector: null,
    allowedRole: 'specialist',
    inputData: 'Campaign goals, audience, platform',
    outputArtifact: 'Campaign plan',
    requiresApproval: false,
    canCallExternal: false,
    status: 'working',
    auditEnabled: true,
    saifRequired: false,
  },
  {
    id: 'skill-social-draft',
    name: 'Social Draft Generation',
    source: 'stitch_native',
    owningCapability: 'GenerateContentDraft',
    boundConnector: 'mcp-content-intelligence',
    allowedRole: 'specialist',
    inputData: 'Campaign request, platform, tone',
    outputArtifact: 'DraftResult[]',
    requiresApproval: false,
    canCallExternal: false,
    status: 'working',
    auditEnabled: true,
    saifRequired: false,
  },
  {
    id: 'skill-platform-adaptation',
    name: 'Platform Adaptation',
    source: 'stitch_native',
    owningCapability: 'GenerateContentDraft',
    boundConnector: 'mcp-content-intelligence',
    allowedRole: 'specialist',
    inputData: 'Draft text, target platform',
    outputArtifact: 'Platform-specific draft',
    requiresApproval: false,
    canCallExternal: false,
    status: 'working',
    auditEnabled: true,
    saifRequired: false,
  },
  {
    id: 'skill-reach-scoring',
    name: 'Reach Scoring',
    source: 'stitch_native',
    owningCapability: 'EvaluateReachReadiness',
    boundConnector: 'mcp-reach-intelligence',
    allowedRole: 'specialist',
    inputData: 'ContentItemId, platform, draftText',
    outputArtifact: 'ReachScore (totalScore + components)',
    requiresApproval: false,
    canCallExternal: false,
    status: 'working',
    auditEnabled: true,
    saifRequired: false,
  },
  {
    id: 'skill-best-time',
    name: 'Best Time Recommendation',
    source: 'stitch_native',
    owningCapability: 'EvaluateReachReadiness',
    boundConnector: 'mcp-reach-intelligence',
    allowedRole: 'specialist',
    inputData: 'Platform, audience, content type',
    outputArtifact: 'Recommended time slot',
    requiresApproval: false,
    canCallExternal: false,
    status: 'mock',
    auditEnabled: true,
    saifRequired: false,
  },
  {
    id: 'skill-hashtag-hygiene',
    name: 'Hashtag Hygiene',
    source: 'stitch_native',
    owningCapability: 'EvaluateReachReadiness',
    boundConnector: 'mcp-reach-intelligence',
    allowedRole: 'specialist',
    inputData: 'Platform, content topic',
    outputArtifact: 'Validated hashtag list',
    requiresApproval: false,
    canCallExternal: false,
    status: 'mock',
    auditEnabled: true,
    saifRequired: false,
  },
  {
    id: 'skill-approval-routing',
    name: 'Approval Routing',
    source: 'stitch_native',
    owningCapability: 'RequestApproval',
    boundConnector: null,
    allowedRole: 'specialist',
    inputData: 'Content, risk category, department',
    outputArtifact: 'Approval request',
    requiresApproval: true,
    canCallExternal: false,
    status: 'working',
    auditEnabled: true,
    saifRequired: false,
  },
  {
    id: 'skill-publishing-prep',
    name: 'Publishing Preparation',
    source: 'stitch_native',
    owningCapability: 'PreparePublishingPackage',
    boundConnector: 'mcp-postiz-scheduling',
    allowedRole: 'specialist',
    inputData: 'Approved content, platforms, schedule',
    outputArtifact: 'PublishingPackage',
    requiresApproval: true,
    canCallExternal: false,
    status: 'working',
    auditEnabled: true,
    saifRequired: true,
  },
  {
    id: 'skill-analytics-summary',
    name: 'Analytics Summary',
    source: 'stitch_native',
    owningCapability: 'GenerateFinancialReport',
    boundConnector: 'mcp-social-analytics',
    allowedRole: 'specialist',
    inputData: 'Campaign ID, date range',
    outputArtifact: 'PerformanceReport',
    requiresApproval: false,
    canCallExternal: false,
    status: 'mock',
    auditEnabled: true,
    saifRequired: false,
  },
  {
    id: 'skill-lead-qualification',
    name: 'Lead Qualification',
    source: 'mcp_imported',
    owningCapability: 'CaptureLead',
    boundConnector: 'mcp-lead-qualification',
    allowedRole: 'specialist',
    inputData: 'Lead data, campaign attribution',
    outputArtifact: 'Qualified lead score',
    requiresApproval: false,
    canCallExternal: false,
    status: 'mock',
    auditEnabled: true,
    saifRequired: false,
  },
  {
    id: 'skill-ghl-handoff',
    name: 'GoHighLevel CRM Handoff Preparation',
    source: 'planned_mcp',
    owningCapability: 'CaptureLead',
    boundConnector: 'mcp-ghl-crm',
    allowedRole: 'specialist',
    inputData: 'Qualified lead, campaign data',
    outputArtifact: 'CRM handoff payload',
    requiresApproval: true,
    canCallExternal: false,
    status: 'planned',
    auditEnabled: true,
    saifRequired: true,
  },
  {
    id: 'skill-whatsapp-handoff',
    name: 'WhatsApp Handoff Preparation',
    source: 'planned_mcp',
    owningCapability: 'CaptureLead',
    boundConnector: 'mcp-whatsapp',
    allowedRole: 'specialist',
    inputData: 'Lead data, message template',
    outputArtifact: 'Message preparation payload',
    requiresApproval: true,
    canCallExternal: false,
    status: 'planned',
    auditEnabled: true,
    saifRequired: true,
  },
  {
    id: 'skill-voice-chat-handoff',
    name: 'Voice/Chat Agent Handoff Preparation',
    source: 'planned_mcp',
    owningCapability: 'CaptureLead',
    boundConnector: 'mcp-voice-chat',
    allowedRole: 'department_head',
    inputData: 'Lead data, engagement context',
    outputArtifact: 'Agent handoff payload',
    requiresApproval: true,
    canCallExternal: false,
    status: 'planned',
    auditEnabled: true,
    saifRequired: true,
  },
  {
    id: 'skill-audit-evidence',
    name: 'Audit / SPINE Evidence',
    source: 'stitch_native',
    owningCapability: 'PreparePublishingPackage',
    boundConnector: null,
    allowedRole: 'viewer',
    inputData: 'Run ID, campaign ID',
    outputArtifact: 'SPINE timeline, audit records',
    requiresApproval: false,
    canCallExternal: false,
    status: 'working',
    auditEnabled: true,
    saifRequired: false,
  },
];

export const GHL_READINESS = {
  purpose: 'Lead capture, qualification, CRM handoff, opportunity creation',
  currentState: 'Mock/Planned',
  demoState: 'Prepared handoff payload only',
  realCrmWrites: 'Blocked',
  requiredCredentials: [
    { name: 'GHL_API_KEY', description: 'GoHighLevel API key or OAuth credential', status: 'missing' },
    { name: 'GHL_LOCATION_ID', description: 'GoHighLevel location ID', status: 'missing' },
    { name: 'GHL_PIPELINE_ID', description: 'GoHighLevel pipeline ID', status: 'missing' },
  ],
  requiredApprovals: ['Human approval', 'CRM write authorization', 'M5 execution approval for write-back'],
  dataBoundary: ['No real PII in demo', 'No real contact creation', 'No real opportunity update', 'No WhatsApp/DM automation'],
  futurePath: 'STITCH → SAIF Approval Gateway → MCP Connector Layer → GoHighLevel CRM',
};

export const CONTENT_ALGO_READINESS = {
  capabilities: [
    { name: 'Content Intelligence', status: 'mock', label: 'Demo intelligence, official API connectors planned' },
    { name: 'Platform Algorithm Rules', status: 'mock', label: 'Deterministic rules, official API planned' },
    { name: 'Best Time Recommendation', status: 'mock', label: 'Demo rules, official analytics planned' },
    { name: 'Format Recommendation', status: 'mock', label: 'Demo rules, official API planned' },
    { name: 'Hashtag Hygiene', status: 'mock', label: 'Demo rules, official API planned' },
    { name: 'Reach/Readiness Scoring', status: 'working', label: 'Deterministic scoring engine' },
    { name: 'Learning Signals', status: 'mock', label: 'Demo signals, closed-loop planned' },
  ],
  futurePath: 'STITCH → SAIF → MCP → Official Social APIs / Postiz / Analytics Sources',
};
