import { AppError } from '@shared/errors';
import { auditLog } from '@shared/logging';
import { resolveUserLLMProvider } from '@modules/ai-provider/controller';
import { checkHistoricalAssessmentPermission } from './policy';
import * as repo from './repository';
import {
  generatedAssessmentSchema,
  type AssessmentScopeInput,
  type CreateAssessmentRunInput,
  type DecideAssessmentFindingInput,
  type ListAssessmentRunsInput,
} from './types';

const SYSTEM_PROMPT = [
  'You are Stitchi, Tanaghum\'s evidence-grounded commercial assessment analyst.',
  'Analyze only the supplied immutable evidence snapshot.',
  'Never invent sales, spend, reach, leads, purchases, audience behavior, or success criteria.',
  'Every finding must cite one or more supplied evidence IDs.',
  'Use Repeat for a proven strength, Improve for an underperforming area, Avoid for a harmful pattern, and Investigate when evidence is incomplete or contradictory.',
  'Return JSON only, matching the requested schema. Do not include markdown fences.',
].join(' ');

export async function previewAssessment(role: string, tenantKey: string, input: AssessmentScopeInput) {
  checkHistoricalAssessmentPermission(role, 'assessment:read');
  return repo.previewEvidence(tenantKey, input);
}

export async function createAssessment(
  role: string,
  tenantKey: string,
  userId: string,
  input: CreateAssessmentRunInput,
) {
  checkHistoricalAssessmentPermission(role, 'assessment:create');
  const preview = await repo.previewEvidence(tenantKey, input);
  const run = await repo.createAssessmentRun(tenantKey, userId, input, preview);
  auditLog(
    { actor: `user:${userId}`, action: 'historical_assessment_created', object_type: 'commercial_historical_assessment_run', object_id: run.id, result: 'success' },
    `Historical assessment created with ${preview.evidence.length} evidence record(s)`,
  );
  return repo.serializeAssessment(run);
}

export async function listAssessments(role: string, tenantKey: string, input: ListAssessmentRunsInput) {
  checkHistoricalAssessmentPermission(role, 'assessment:read');
  return repo.serializeAssessment(await repo.listAssessmentRuns(tenantKey, input));
}

export async function getAssessment(role: string, tenantKey: string, id: string) {
  checkHistoricalAssessmentPermission(role, 'assessment:read');
  return repo.serializeAssessment(await repo.getAssessmentRun(tenantKey, id));
}

export async function generateAssessment(role: string, tenantKey: string, userId: string, id: string) {
  checkHistoricalAssessmentPermission(role, 'assessment:generate');
  const run = await repo.startGeneration(tenantKey, id);
  try {
    const provider = await resolveUserLLMProvider(userId);
    const status = provider.getStatus();
    const response = await provider.generate(buildPrompt(run), {
      systemPrompt: SYSTEM_PROMPT,
      maxTokens: 1800,
      temperature: 0.15,
      timeoutMs: 45000,
    });
    const generated = generatedAssessmentSchema.parse(parseJsonResponse(response.text));
    const saved = await repo.saveGeneratedFindings(tenantKey, userId, id, generated, {
      type: response.provider || status.type,
      model: response.model || status.model || null,
    });
    auditLog(
      { actor: `user:${userId}`, action: 'historical_assessment_ai_generated', object_type: 'commercial_historical_assessment_run', object_id: id, result: 'success' },
      `Historical assessment generated by ${response.provider || status.type}`,
    );
    return repo.serializeAssessment(saved);
  } catch (error) {
    const reason = safeFailureReason(error);
    await repo.markGenerationFailed(tenantKey, id, reason);
    auditLog(
      { actor: `user:${userId}`, action: 'historical_assessment_ai_generation_failed', object_type: 'commercial_historical_assessment_run', object_id: id, result: 'failure' },
      reason,
    );
    throw error;
  }
}

export async function decideFinding(
  role: string,
  tenantKey: string,
  userId: string,
  findingId: string,
  input: DecideAssessmentFindingInput,
) {
  checkHistoricalAssessmentPermission(role, 'assessment:approve');
  return repo.serializeAssessment(await repo.decideFinding(tenantKey, userId, findingId, input));
}

export async function listLearningSets(role: string, tenantKey: string) {
  checkHistoricalAssessmentPermission(role, 'assessment:read');
  return repo.serializeAssessment(await repo.listLearningSets(tenantKey));
}

function buildPrompt(run: Awaited<ReturnType<typeof repo.startGeneration>>): string {
  const evidence = run.evidence.slice(0, 120).map(item => ({
    id: item.id,
    type: item.evidence_type,
    sourceName: item.source_name,
    metricKey: item.metric_key,
    metricValue: item.metric_value,
    metricUnit: item.metric_unit,
    observedAt: item.observed_at,
    payload: item.payload,
  }));
  return JSON.stringify({
    task: 'Analyze historical commercial performance and propose evidence-backed learning for future planning.',
    outputSchema: {
      findings: [{
        type: 'repeat | improve | avoid | investigate',
        title: 'short title',
        summary: 'what the evidence shows',
        recommendation: 'what future planning should do',
        confidence: 'number from 0 to 1',
        evidenceIds: ['one or more IDs from evidence'],
      }],
    },
    assessment: {
      id: run.id,
      title: run.title,
      dateFrom: run.date_from,
      dateTo: run.date_to,
      evidenceSummary: run.evidence_summary,
      knownMissingData: run.missing_data,
      evidenceIncluded: evidence.length,
      evidenceTotal: run.evidence.length,
    },
    evidence,
  });
}

function parseJsonResponse(text: string): unknown {
  const trimmed = text.trim();
  const fenced = /^```(?:json)?\s*([\s\S]*?)\s*```$/i.exec(trimmed);
  const candidate = fenced?.[1] || trimmed;
  const start = candidate.indexOf('{');
  const end = candidate.lastIndexOf('}');
  if (start < 0 || end <= start) {
    throw new AppError('AI returned no valid assessment JSON', 502, 'AI_ASSESSMENT_INVALID_RESPONSE');
  }
  try {
    return JSON.parse(candidate.slice(start, end + 1));
  } catch {
    throw new AppError('AI returned malformed assessment JSON', 502, 'AI_ASSESSMENT_INVALID_RESPONSE');
  }
}

function safeFailureReason(error: unknown): string {
  if (error instanceof AppError) return error.message;
  return error instanceof Error && error.message
    ? `Assessment generation failed: ${error.message.slice(0, 700)}`
    : 'Assessment generation failed because the AI provider returned an unexpected error.';
}
