import { useEffect, useState } from 'react';
import { analyticsApi } from '../api';
import { useAuth } from '../contexts/useAuth';
import { ExecutiveMetric, RecommendationCard, Badge } from '../components/ExecutiveUI';

type AnalyticsDemo = {
  impressions?: number;
  reach?: number;
  engagementRate?: string;
  bestPlatform?: string;
  topContent?: string;
  bestTime?: string;
  _label?: string;
};

export default function Analytics() {
  const { token } = useAuth();
  const [demo, setDemo] = useState<AnalyticsDemo | null>(null);

  useEffect(() => {
    if (!token) return;
    analyticsApi.demo(token)
      .then(d => setDemo(d as AnalyticsDemo))
      .catch(console.error);
  }, [token]);

  const reach = demo?.reach ?? 0;
  const impressions = demo?.impressions ?? 0;
  const engagementRate = demo?.engagementRate ?? 'checking';

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-white">Analytics Intelligence</h1>
          <p className="text-slate-500 text-sm mt-0.5">Backend demo intelligence. Official read-only social APIs require separate authorization.</p>
        </div>
        <div className="flex items-center gap-2">
          <Badge variant="mock">Demo analytics provider</Badge>
          <Badge variant="blocked">No live social API calls</Badge>
        </div>
      </div>

      <div className="grid grid-cols-5 gap-3">
        <ExecutiveMetric label="Reach" value={demo ? reach.toLocaleString() : '...'} sublabel="Demo snapshot" trend="up" />
        <ExecutiveMetric label="Impressions" value={demo ? impressions.toLocaleString() : '...'} sublabel="Demo snapshot" trend="up" />
        <ExecutiveMetric label="Engagement" value={engagementRate} sublabel="Normalized rate" trend="up" />
        <ExecutiveMetric label="Best Platform" value={demo?.bestPlatform || '...'} sublabel="Recommendation" />
        <ExecutiveMetric label="Best Time" value={demo?.bestTime || '...'} sublabel="Recommendation" />
      </div>

      <div className="grid grid-cols-[1.2fr_1fr] gap-6">
        <div className="rounded-xl border border-slate-800 bg-slate-950/70 p-5">
          <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-4">Performance Signal</h3>
          <div className="rounded-xl border border-slate-800 bg-slate-900/70 p-5">
            <div className="flex items-start justify-between gap-4">
              <div>
                <div className="text-sm font-semibold text-white">{demo?.topContent || 'Loading top content signal...'}</div>
                <p className="mt-2 text-sm leading-6 text-slate-400">
                  This is a controlled analytics snapshot generated by STITCH for the demo. It is suitable for showing
                  the decision workflow, not for claiming live platform performance.
                </p>
              </div>
              <Badge variant="info">Learning input</Badge>
            </div>
            <div className="mt-5 grid grid-cols-3 gap-3">
              {[
                ['Signal quality', 'High'],
                ['API source', 'Demo provider'],
                ['Writeback', 'Blocked'],
              ].map(([label, value]) => (
                <div key={label} className="rounded-lg bg-slate-950 p-3">
                  <div className="text-xs uppercase tracking-wider text-slate-500">{label}</div>
                  <div className="mt-1 text-sm font-semibold text-slate-200">{value}</div>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div className="rounded-xl border border-slate-800 bg-slate-950/70 p-5">
          <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-4">AI Recommendations</h3>
          <div className="space-y-3">
            <RecommendationCard title="Best Platform" value={demo?.bestPlatform || 'LinkedIn'} confidence={85} />
            <RecommendationCard title="Best Time" value={demo?.bestTime || 'Tuesday 10:00 AM'} confidence={78} />
            <RecommendationCard title="Best Format" value="Educational post with image" confidence={82} />
            <RecommendationCard title="Hashtag Hygiene" value="3-5 relevant tags" confidence={70} />
          </div>
        </div>
      </div>

      <div className="rounded-xl border border-slate-800 bg-slate-950/70 p-5">
        <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-4">Integration Roadmap</h3>
        <div className="grid grid-cols-6 gap-3">
          {[
            { phase: '1', desc: 'Demo analytics and package prep', status: 'current' },
            { phase: '2', desc: 'Official read-only analytics APIs', status: 'planned' },
            { phase: '3', desc: 'Approval-gated Postiz scheduling', status: 'planned' },
            { phase: '4', desc: 'GoHighLevel lead qualification', status: 'planned' },
            { phase: '5', desc: 'Voice/chat handoff package', status: 'planned' },
            { phase: '6', desc: 'Closed-loop learning', status: 'planned' },
          ].map(p => (
            <div key={p.phase} className="rounded-lg border border-slate-800 bg-slate-900/70 p-3 text-center">
              <div className="text-lg font-bold text-slate-500">{p.phase}</div>
              <div className="mt-1 min-h-[48px] text-xs text-slate-400">{p.desc}</div>
              <Badge variant={p.status === 'current' ? 'info' : 'default'}>{p.status}</Badge>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
